### ISSUE TITLE
"Operation Timeout Error" on first load for AWS Lambda with SSM

### ISSUE THREAD

**Issue by RyanSchaefer** [slackapi/bolt-python#155]
I am experiencing an issue when running slack bolt on AWS Lambda, specifically the module does not load fast enough for the `ack()` to be sent before 3 seconds on first load. Whenever the loaded modules are no longer cached, this issue happens again. We moved to slack bolt from a previous method where we had an SQS queue -> Lambda -> Lambda where the first lambda would return a `200` and the second would do the actual processing because slack bolt promises to be more simple and feature rich. We have some special wrapping to support creating a Class wrapper around the app to prevent issues with caching global variables in Lambda as well as support for a single entrypoint `/command` from which a subcommand can be supplied with arguments in order to support more dynamic additions of commands to the bot without needing to create extra `/commands` on api.slack.com. 

My main question is: Are we using this module incorrectly or is there some sort of tuning we can preform to eliminate this error?

### Reproducible in:

MCVE
```python
def supply_self(func, this):
    """
    Adapts from a three argument function to a two argument function
    :param func: the function to supply self to
    :param this: renamed self to prevent conflicts with how bolt wires its functions
    :return: a function which can be called by bolt
    """
    return lambda respond, body: func(this, respond, body)

class BasicBot:
    """
    Instead of making app global (which could cause caching issues), we want to make it a field of an object we can create
    """

    def __init__(self, entrypoint_name: str, *args):
        self.app = slack_bolt.App(process_before_response=True,
                                  signing_secret=SSMParameter(os.environ["SIGNING_SECRET_LOCATION"], max_age=3600).value,
                                  token=SSMParameter(os.environ["SLACK_API_LOCATION"], 3600).value)
        self.app.command(entrypoint_name)(ack=lambda body, ack: ack(),
                                                  # unable to call self.func here because slack bolt assumes
                                                  # procedural code, by supplying self as a different argument we can
                                                  # circumvent this
                                                  lazy=[supply_self(func, self)])
        # the above `func` comes from a decorated method within the class
        # ...

def lambda_handler(event, context):
    aws_lambda_logging.setup(aws_request_id=context.aws_request_id, level="INFO")
    logging.info(event)
    bot = BasicBot(os.environ["COMMAND_ENTRYPOINT"])
    return SlackRequestHandler(app=bot.app).handle(event, context)
```
#### The `slack_bolt` version

Latest version

#### Python runtime version

3.8

#### OS info

AWS Lambda's python environment

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Deploy Labmda
2. call `/entrypoint` with some `say()`
3. observe operation timeout
4. observe `say()` message being sent
5. call `/entrypoint` again
6. observe no timeout

### Expected result:

No "Operation Timeout Error" on first call

### Actual result:

Timeout when module is not cached then no timeout when Lambda caches it. Message is sent in both cases but the first degrades user experience. 

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Thanks for asking the question. I can check the actual behavior by deploying a Lambda function with a similar structure later. Before that, let me share some general thoughts on this:

* I have been operating a Bolt for Python app running on AWS Lambda for a while and the app never encounters cold-start issues. `slack_bolt` depends on `slack_sdk` package. `slack_sdk` does not have any additional dependencies(!). So, loading only these modules should not take so long.
* JFYI: This is not specific to Bolt. When I tried AWS Chalice library for Slack apps, I often encountered cold-starts and Slack app 3 second timeouts with it. I think Chalice is an amazing library and it is a great fit for many use cases. However, specifically for Slack apps, it may not be a better solution than a thin Lambda function.
* Similarly, I think some other dependencies may take a bit long for their initialization. From my past experience, I needed to warm AWS S3 client (by the AWS Java SDK) instances up as it takes long for initialization. I don't think using `SSMParameter` costs but if something similar is happening to your app, that makes sense. If this assumption is correct, you can move the initialization to the lazy function (this means moving heavy module imports and/or initialization to the inside of a lazy function.
* I'm curious about the `with some say()` in your repro steps. Do you have these API calls in the `ack()` listener function or in one of lazy functions? If you have it in ack function, you can move it to lazy functions. The response time from the Slack API server is consistent but if performing multiple Slack API calls in ack function, it is not recommended.

If you already have a minimal working example that reproduces the issue, sharing the source is helpful to understand your issue.

**Comment by RyanSchaefer** [comment]
We are using SAM rather than chalice. So here is a minimal template to deploy:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  QueueProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Events:
        HttpApiEvent:
          Type: HttpApi
      Handler: # ... lambda_handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
            # function must be able to call itself in order to 1st handle acking within 3 seconds then 2nd
            # process the actual message
            - Effect: Allow
              Action: "lambda:InvokeFunction"
              Resource: !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-*"
```

The `ack()` is separate from the response. I tried refactoring to this:
```python
app = slack_bolt.App(process_before_response=True,
                                     signing_secret=SSMParameter(os.environ["SIGNING_SECRET_LOCATION"], max_age=3600).value,
                                     token=SSMParameter(os.environ["SLACK_API_LOCATION"], 3600).value)
app.event(re.compile(".*"))(
            ack=lambda body, ack: ack(),
            lazy=[lambda respond, body: ECSBot(ecs_monitoring.ECSMonitor()).handle_response(event, context)])
```
to basically `ack()` the message as soon as possible but I think that, again, the fetching the `SSMParameter` is taking too long and pushing the `ack()` back enough that causes a timeout. Enough is cached that on subsequent calls there are no issues. 

It's just tricky because I essentially need an `App` without secrets to handle the initial `ack()`, then once that is processed I can do as much processing/loading as I want. 

With regards to the last point. I actually use `respond()` in a function seperate from the `ack`. As you can see in the intially posted code, my `ack` is a minimal function which just calls the `ack` provided to it:

```python
ack=lambda body, ack: ack()
```
