### ISSUE TITLE
How can i use bolt with event subscription + worker + oauth

### ISSUE THREAD

**Issue by RomanNovo** [slackapi/bolt-python#498]
Currently using OAuthFlow.sqlite3. Trying to do simple task - 
1. generate task for worker from event 
2. store task in sqlite db
3. worker get tasks every n-hours and perform it

on 3 step i have got issue - how to authorize worker through OAuth along with main app? I am tryed to use installation_store but after 1-2 tasks receive a auth error.

**Comment by RomanNovo** [comment]
```
bot: Bot = tmp_slack_app.installation_store.find_bot(team_id="T666666666", enterprise_id="")
client = tmp_slack_app.client 
rotator = TokenRotator(client_secret=client_secret, client_id=client_id, client=client)
newBot : Bot = rotator.perform_bot_token_rotation(bot=bot, minutes_before_expiration=60 * 24)
    if newBot : 
        tmp_slack_app.installation_store.save_bot(newBot)
        client.token = newBot.bot_token
```

**Comment by seratch** [comment]
@RomanNovo I've created a simple example app and tried to reproduce your situation but I haven't managed to see any errors. 

Can you check the difference between my example below and your app? Also, if you are fine to share log outputs about the error you are seeing, more detailed information would be helpful to understand the situation.

main.py:
```python
# To run this app
# export SLACK_CLIENT_ID=
# export SLACK_CLIENT_SECRET=
# export SLACK_SIGNING_SECRET=
# python main.py
import os
from slack_bolt import App
from slack_bolt.oauth.oauth_flow import OAuthFlow

oauth_flow = OAuthFlow.sqlite3(
    database="./database",
    client_id=os.environ["SLACK_CLIENT_ID"],
    client_secret=os.environ["SLACK_CLIENT_SECRET"],
    scopes=["commands", "chat:write"],
    # If you use only bot table for installation management, setting this to True is recommended
    # Refer to https://github.com/slackapi/bolt-python/releases/tag/v1.1.2 for more details
    installation_store_bot_only=True,
)

app = App(
    signing_secret=os.environ["SLACK_SIGNING_SECRET"],
    oauth_flow=oauth_flow
)

@app.command("/hello-python-token-rotation")
def handle_some_command(ack):
    ack("Hi there!")

if __name__ == "__main__":
    import logging
    logging.basicConfig(level=logging.DEBUG)
    app.start(port=int(os.environ.get("PORT", 3000)))
```

worker.py:
```python
# To run this app
# export SLACK_CLIENT_ID=
# export SLACK_CLIENT_SECRET=
# export SLACK_SIGNING_SECRET=
# python worker.py
import logging
logging.basicConfig(level=logging.DEBUG)

from main import app, oauth_flow

from slack_sdk.oauth.token_rotation import TokenRotator
rotator = TokenRotator(
    client_secret=oauth_flow.settings.client_secret,
    client_id=oauth_flow.settings.client_id,
)

# TODO: change the following IDs with your own ones
enterprise_id=None
team_id="T11111"
bot = app.installation_store.find_bot(enterprise_id=enterprise_id, team_id=team_id)

refreshed_bot = rotator.perform_bot_token_rotation(bot=bot, minutes_before_expiration=60*24)
print(refreshed_bot)

app.installation_store.save_bot(refreshed_bot)

from slack_sdk import WebClient
client = WebClient()
client.auth_test(token=refreshed_bot.bot_token)
```

App Manifest:
```yaml
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: python-token-rotation-app
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: false
    messages_tab_read_only_enabled: true
  bot_user:
    display_name: python-token-rotation-app
  slash_commands:
    - command: /hello-python-token-rotation
      description: test
      usage_hint: test
      url: https://your.ngrok.io/slack/events
oauth_config:
  scopes:
    bot:
      - commands
      - chat:write  
  redirect_urls:
    - https://your.ngrok.io/slack/oauth_redirect
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: true
```
