### ISSUE TITLE
How to know the user id of the receiving user?

### ISSUE THREAD

**Issue by SamarpanRai-TomTom** [slackapi/bolt-python#557]
My goal is to create an automated "voice mail" for users when they are not available. 

Say there are three users - A, B, C. Arrow pointing outward means a user is sending a message to another user. 
```
User A -> User B
User A -> User C 
```
Assume that user B and user C have installed my Slack app but user A hasn't. Now, my question is how can I get the `WebClient` based on the receiving user? 

I need to know the right `WebClient` such that I can respond to the sending user on their behalf. That is, when User A sends a message to user B then I want to respond on behalf of User B.

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version

(Paste the output of `pip freeze | grep slack`)
slack-bolt==1.11.0
slack-sdk==3.11.2

#### Python runtime version

(Paste the output of `python --version`)
3.8.0

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
ProductName:    macOS
ProductVersion: 12.1
BuildVersion:   21C52
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64

### Expected result:

Get the `WebClient` of the receiving user

### Actual result:
Get the `WebClient` of the installed user

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @SamarpanRai-TomTom, I assume that you are trying to build an app that subscribes to user events. Here is a simple App Manifest for such an app:

```yaml
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: user-token-socket-mode-app
oauth_config:
  scopes:
    user:
      - im:history
      - chat:write
settings:
  event_subscriptions:
    user_events:
      - message.im
```

If this is correct,

> my question is how can I get the WebClient based on the receiving user?

You can use `event.user` to know the user who posted a message in DM. To know who received a message from someone else in his/her DM, you can use `authorizations[0].user_id` for it. Perhaps, the latter one is the data that you're interested in.

I hope this helps.
