### ISSUE TITLE
How to trigger view_closed events?

### ISSUE THREAD

**Issue by smoneta** [slackapi/bolt-python#624]
Hello team, I'm trying to capture the action of closing a modal from the X or the cancel button. I set up the call using the view_closed with the callback id used when creating the modal and to test I just print a message but I don't get anything.

#### The `slack_bolt` version

slack-bolt==1.13.0
slack-sdk==3.10.1

#### Python runtime version

Python 3.9.2

#### OS info

MacOS Monterrey 12.3
Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64

#### Steps to reproduce:

When creating the modal:
```
...
},
        "close": {
            "type": "plain_text",
            "text": "Close",
            "emoji": True
        },
        "callback_id": "file_info",
        "blocks": [
            {
                "type": "actions",
                "elements": [
...
```

Then on my main.py file:

```
@app.view_closed("file_info")
def handle_some_action(body):
    print(f'The modal have been closed:{body}')
```

### Expected result:

When I close the modal from X or cancel I should see the line `The modal have been closed: ` and the payload printed in the console.

### Actual result:

Nothing shows up in the console (except other messages from the same app)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @smoneta, can you try out the following example code? Having `notify_on_close` property is the key.

app.py

```python
import logging
import os

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_sdk import WebClient

logging.basicConfig(level=logging.DEBUG)

app = App(token=os.environ.get("SLACK_BOT_TOKEN"))

@app.shortcut("test-global-shortcut")
def handle_shortcuts(ack, body, client: WebClient):
    ack()
    client.views_open(
        trigger_id=body.get("trigger_id"),
        view={
            "type": "modal",
            "callback_id": "modal-id",
            "title": {
                "type": "plain_text",
                "text": "Modal title"
            },
            "blocks": [],
            "close": {
                "type": "plain_text",
                "text": "Cancel"
            },
            "notify_on_close": True,  # This attribute is required
        }
    )

@app.view_closed("modal-id")
def handle_view_closed(ack, body, logger):
    ack()
    logger.info("--------------- view_closed handler called ---------------")
    logger.info(body)

if __name__ == "__main__":
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).start()
```

App Manifest (YAML):

```yaml
display_information:
  name: test-socket-mode-app
features:
  bot_user:
    display_name: test-socket-mode-app
  shortcuts:
    - name: test-global-shortcut
      type: global
      callback_id: test-global-shortcut
      description: test
oauth_config:
  scopes:
    bot:
      - commands
settings:
  interactivity:
    is_enabled: true
  socket_mode_enabled: true
```

I hope this was helpful to you.
